version: "3.9"
volumes:
  # chat-demo-socket:
  # name: chat-demo-socket
  chat-demo-node-modules:
    name: chat-demo-node-modules

networks:
  chat-demo-network:
    name: chat-demo-network

services:
  chat-demo-proxy:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: chat-demo-proxy
    ports:
      - "8087:80"
    depends_on:
      - chat-demo-backend
      - chat-demo-frontend
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      # - "chat-demo-socket:/var/run/php-fpm/"
      # - ./docker/web/proxy-php.conf:/usr/local/apache2/conf/extra/proxy-php.conf
    environment:
      - TZ=Asia/Tokyo
    networks:
      - chat-demo-network
    
  chat-demo-frontend:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    container_name: chat-demo-frontend
    networks:
      - chat-demo-network
    volumes:
      - ./frontend:/var/www
      - chat-demo-node-modules:/var/www/node_modules
    command: sh -c "yarn install && yarn serve"

  chat-demo-backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: chat-demo-backend
    volumes:
      # - "chat-demo-socket:/var/run/php-fpm/"
      - ./backend:/var/www/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/database.sqlite:/database.sqlite
    depends_on:
      - chat-demo-db
    networks:
      - chat-demo-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=chat-demo-db
      - DB_PORT=3306
      - DB_DATABASE=chat_db
      - DB_USERNAME=chat
      - DB_PASSWORD=chat

  chat-demo-db:
    image: mysql:8.0
    container_name: chat-demo-db
    networks:
      - chat-demo-network
    ports:
      - 43306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: chat
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
