name: Test

on:
  push:
    branches: [ main, develop, feature/github-actions]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dokcer-compose up
      run: |
        # docker-compose build
        docker-compose up -d --wait
    - name: composer install
      run: |
        docker exec chat-demo-backend  /bin/sh -c "composer install"
    - name: phpunit
      run: |
        docker exec chat-demo-backend  /bin/sh -c  "php vendor/bin/phpunit"